// data.js
export const industries = [
    "CEMENT INDUSTRY",
    "PHARMACEUTICAL & BULK DRUGS",
    "REFINERIES",
    "POWER INDUSTRIES",
    "AUTOMOBILE INDUSTRIES",
    "PROCESS INDUSTRIES",
    "PAPER INDUSTRIES",
    "STEEL INDUSTRIES",
    "CHEMICALS & FERTILIZERS"
];

export const clientsData = {
    "CEMENT INDUSTRY": [
        { id: "cement-1", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-2", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-3", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-4", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-5", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-6", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-7", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-8", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-9", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-10", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-11", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-12", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" }
    ],
    "PHARMACEUTICAL & BULK DRUGS": [
        { id: "pharma-1", name: "CAPILA LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Pithampur (MP)", projectValue: "Approx value 955 Lacs" },
        { id: "pharma-2", name: "RANBAXY LABORATORIES LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Dewas (M.P)", projectValue: "Approx value 200 Lacs" },
        { id: "cement-3", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-4", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-5", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-6", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-7", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-8", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-9", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-10", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
    ],
    "REFINERIES": [
        { id: "refinery-1", name: "RELIANCE INDUSTRIES LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Jamnagar, Gujarat", projectValue: "Approx value 1500 Lacs" },
        { id: "refinery-2", name: "BHARAT PETROLEUM CORP. LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Mumbai, Maharashtra", projectValue: "Approx value 980 Lacs" },
        { id: "cement-3", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-4", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-5", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-6", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-7", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-8", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-9", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-10", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
    ],
    "POWER INDUSTRIES": [
        { id: "power-1", name: "NTPC LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Pan-India", projectValue: "Approx value 1100 Lacs" },
        { id: "power-2", name: "TATA POWER CO. LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Maharashtra", projectValue: "Approx value 900 Lacs" },
        { id: "cement-3", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-4", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-5", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-6", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-7", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-8", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-9", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-10", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
    ],
    "AUTOMOBILE INDUSTRIES": [
        { id: "auto-1", name: "MARUTI SUZUKI INDIA LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gurgaon, Haryana", projectValue: "Approx value 750 Lacs" },
        { id: "auto-2", name: "TATA MOTORS LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Pune, Maharashtra", projectValue: "Approx value 600 Lacs" },
        { id: "cement-3", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-4", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-5", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-6", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-7", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-8", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-9", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-10", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
    ],
    "PROCESS INDUSTRIES": [
        { id: "process-1", name: "L&T PROCESS ENGINEERING", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Chennai, Tamil Nadu", projectValue: "Approx value 500 Lacs" },
        { id: "process-2", name: "ABB INDIA LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Bangalore, Karnataka", projectValue: "Approx value 450 Lacs" },
        { id: "cement-3", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-4", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-5", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-6", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-7", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-8", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-9", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-10", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
    ],
    "PAPER INDUSTRIES": [
        { id: "paper-1", name: "JK PAPER LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Odisha", projectValue: "Approx value 300 Lacs" },
        { id: "paper-2", name: "BALLARPUR INDUSTRIES LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Maharashtra", projectValue: "Approx value 250 Lacs" },
        { id: "cement-3", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-4", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-5", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-6", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-7", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-8", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-9", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-10", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
    ],
    "STEEL INDUSTRIES": [
        { id: "steel-1", name: "SAIL (STEEL AUTHORITY OF INDIA)", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Bhilai, Chhattisgarh", projectValue: "Approx value 1300 Lacs" },
        { id: "steel-2", name: "TATA STEEL LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Jamshedpur, Jharkhand", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-3", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-4", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-5", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-6", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-7", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-8", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-9", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-10", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
    ],
    "CHEMICALS & FERTILIZERS": [
        { id: "chem-1", name: "GUJARAT STATE FERTILIZERS & CHEMICALS", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Vadodara, Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "chem-2", name: "IFFCO (INDIAN FARMERS FERTILIZER CO-OPERATIVE)", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Across India", projectValue: "Approx value 950 Lacs" },
        { id: "cement-3", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-4", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-5", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-6", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-7", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-8", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
        { id: "cement-9", name: "ULTRATECH CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Multiple Locations", projectValue: "Approx value 1200 Lacs" },
        { id: "cement-10", name: "AMBUJA CEMENT LTD.", logo: "https://shreeengineers.in/images2/brands/client-11.png", location: "Gujarat", projectValue: "Approx value 850 Lacs" },
    ]
};
